### ISSUE TITLE
`fetch-quickstarts` workflow failing

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/instant-observability-website#15]
## Description
The `fetch-quickstarts` script is receiving a 404 when it tries to enable or disable branch protection on this repository.

- [Workflow file](https://github.com/newrelic/instant-observability-website/blob/main/.github/workflows/fetch-quickstarts.yml)

## Steps to Reproduce

- [Latest run of `fetch-quickstarts](https://github.com/newrelic/instant-observability-website/actions/runs/1773844683)

## Expected Behavior

- Branch protection is disabled so that new quickstarts can be committed and it is re-enabled afterwords

**Comment by rudouglas** [comment]
I wonder if it's something to do with the `OPENSOURCE_BOT_TOKEN` not having permission for the repo, but I would assume we would see a 403 rather than a 404?

**Comment by aswanson-nr** [comment]
@rudouglas I just noticed that we are seeing the same failures for the related resources workflow as well https://github.com/newrelic/instant-observability-website/actions/runs/1775564351

**Comment by rudouglas** [comment]
@aswanson-nr think i've figured this out, the difference I can see is that `OPENSOURCE_BOT_TOKEN` is set as an Organization secret in the new site, rather than a repo secret so I think we will need to give it permissions to alter the repo on the Org level
![Screenshot 2022-02-02 at 14 00 55](https://user-images.githubusercontent.com/17122543/152169229-9d09f8a7-b492-4948-8dcb-3c63dc874c90.jpg)

**Comment by rudouglas** [comment]
To fix this we added the `nr_opensource_bot` as an admin user on the repo
