### ISSUE TITLE
[Public Catalog] Contributors component

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/instant-observability-website#39]
## Summary

Add component to use in the right column to display contributor data for a particular o11y pack.

## Acceptance criteria

- [ ] Need decision on if this is going also available in the product exp.
- [ ] We'd need to obtain the github data for this to pull in the contributor information
- [ ] Displays top contributors to the particular Olly Pack (directory)
- [ ] Provides a link to the repo so a user can easily contribute to the pack repo

### Visual Design

<img width="330" alt="Screen Shot 2021-05-26 at 8 13 02 PM" src="https://user-images.githubusercontent.com/1395158/119755221-e306a980-be5e-11eb-869c-d0f2cba00367.png">

**Comment by hveerendranath** [comment]
@jpvajda is this under scope of CXPUI team? if yes i would talk to my EM . Also require some more additional details like what all contributors details to be displayed and when etc.

**Comment by jpvajda** [comment]
@hveerendranath it would be, but you'd want to validate it's something we'd want to actually add to the I/O site as a new feature first, we thought it would be important earlier on in I/O but since the I/O site is becoming more marketing focused, this seems less important to highlight contributors in this way. I'm going to close it for now.
