### ISSUE TITLE
[I/O Site SSR] Cache category filters 

### ISSUE THREAD

**Issue by josephgregoryii** [newrelic/instant-observability-website#78]
## Description

When selecting a category filter on the I/O site, it takes about 1-5 seconds to initially render the results from the API request. After the user clicks around for a bit, some filtering renders faster, and it is inconsistent with load time.

### References

https://www.gatsbyjs.com/docs/conceptual/rendering-options/

## Acceptance Criteria
- [ ] Consider if we need caching done on Fastly and/or Gatsby's side
- [ ] Enable caching on the server
- [ ] Confirm caching is stable and clicking around filters does not trigger 414s
- [ ] report our experience to DevEx so they can continue to consider if they need to optimize the catalog service

**Comment by jpvajda** [comment]
I'd be curious if we have a solution to this.

**Comment by jpvajda** [comment]
We decided to not launch the SSR feature at this time.

REASONS: 

- The performance issues we are seeing with category and page data and search results is too severe for a marketing site. Load times are anywhere from 1 - 5 seconds before caching  and spending time to optimize that doesn’t seem worth it at the moment 
- We are seeing large UI deviations in the internal and external catalogs UI  which is making this service less of a value add to the external site now
- Due to our change in direction internally, our original goal of having parity isn’t valid anymore
- As we learned from our GA releases: Our approach to the site has changed a lot in the past several months, to be strictly marketing focused and not something that needs to be a direct parity of the internal catalog, thus reducing the complexity. 
- This site is transitioning to a team focused on marketing website development, and SSR and an integration with the catalog service is extra complexity that offers little end user value, for just a marketing site
