### ISSUE TITLE
[I/O Site SSR] Tabs not displaying content in quickstart details page

### ISSUE THREAD

**Issue by josephgregoryii** [newrelic/instant-observability-website#81]
Relates to #85 , #80

## Description

When navigating through quickstarts with SSR integrated, most quickstarts' details page lead to a broken page which stops the user from being able to navigate the tabs on the page.

## Steps to reproduce

1. Navigate to the [I/O SSR feature site](https://instantobservabilitywebsitefea.gatsbyjs.io/).
2. Click on a few quickstarts to view their detail page
3. Navigate to one of the tabs
4. Information on tabs are inconsistent and mainly result in a broken page

## Acceptance Criteria

- [ ] Determine the cause of the page not rendering tabs and a possible fix
- [ ] Ensure a user can visit all tabs on quickstart's details page on any quickstart
- [ ] TBD - add some sort of alerting to tell if a quickstart tab details is not displaying (not sure if possible)

**Comment by jpvajda** [comment]
we decided to estimate this after we start assessing what may be broken

**Comment by jpvajda** [comment]
We decided to not launch the SSR feature at this time.

REASONS: 

- The performance issues we are seeing with category and page data and search results is too severe for a marketing site. Load times are anywhere from 1 - 5 seconds before caching  and spending time to optimize that doesn’t seem worth it at the moment 
- We are seeing large UI deviations in the internal and external catalogs UI  which is making this service less of a value add to the external site now
- Due to our change in direction internally, our original goal of having parity isn’t valid anymore
- As we learned from our GA releases: Our approach to the site has changed a lot in the past several months, to be strictly marketing focused and not something that needs to be a direct parity of the internal catalog, thus reducing the complexity. 
- This site is transitioning to a team focused on marketing website development, and SSR and an integration with the catalog service is extra complexity that offers little end user value, for just a marketing site
