### ISSUE TITLE
[I/O Site SSR] Cannot toggle light/dark mode after navigating to quickstart details page

### ISSUE THREAD

**Issue by josephgregoryii** [newrelic/instant-observability-website#85]
Relates to #80, #81

## Summary

This issue may be resolved once we get caching in place with SSR. Currently, when a user navigates to the quickstart details page, the toggle button for dark/light mode does nothing. 

## Steps to reproduce:

1. Navigate to [SSR Feature site](https://instantobservabilitywebsitefea.gatsbyjs.io/)
2. Click on any quickstart (some may be broken. If it is, select a different quickstart)
3. Click on the toggle icon in the global header
4. Clicking the toggle should switch between dark/light mode, and it doesn't do anything.

## Acceptance Criteria
- [ ] Locate the issue that disables the toggle button on a quickstart's details page
- [ ] Ensure that a user can toggle light/dark mode anywhere on the I/O Site

**Comment by jpvajda** [comment]
We decided to not launch the SSR feature at this time.

REASONS: 

- The performance issues we are seeing with category and page data and search results is too severe for a marketing site. Load times are anywhere from 1 - 5 seconds before caching  and spending time to optimize that doesn’t seem worth it at the moment 
- We are seeing large UI deviations in the internal and external catalogs UI  which is making this service less of a value add to the external site now
- Due to our change in direction internally, our original goal of having parity isn’t valid anymore
- As we learned from our GA releases: Our approach to the site has changed a lot in the past several months, to be strictly marketing focused and not something that needs to be a direct parity of the internal catalog, thus reducing the complexity. 
- This site is transitioning to a team focused on marketing website development, and SSR and an integration with the catalog service is extra complexity that offers little end user value, for just a marketing site
