### ISSUE TITLE
[I/O Site SSR] Search field is slow to return results

### ISSUE THREAD

**Issue by josephgregoryii** [newrelic/instant-observability-website#87]
## Summary

When adding input to the search query using SSR, loading the results takes a long time. This may be due to querying nerdgraph after each keystroke.

## Steps to reproduce:

1. Navigate to the [I/O SSR Feature Site](https://instantobservabilitywebsitefea.gatsbyjs.io/)
2. Search for a quickstart in the search input
3. Quickstart results populate after multiple seconds

## Acceptance Criteria 
- [x] https://github.com/newrelic/instant-observability-website/issues/78
- [ ] https://github.com/newrelic/instant-observability-website/issues/82
- [ ] Wait to query the search input after a certain number of keystrokes (TBD)
- [ ] Wait to query the search input after a specified amount of time has elapsed before querying (TBD)

**Comment by jpvajda** [comment]
we wanted to confirm if there is any improvement we can make on the front end or if this is a service issue.

**Comment by jpvajda** [comment]
We decided to not launch the SSR feature at this time.

REASONS: 

- The performance issues we are seeing with category and page data and search results is too severe for a marketing site. Load times are anywhere from 1 - 5 seconds before caching  and spending time to optimize that doesn’t seem worth it at the moment 
- We are seeing large UI deviations in the internal and external catalogs UI  which is making this service less of a value add to the external site now
- Due to our change in direction internally, our original goal of having parity isn’t valid anymore
- As we learned from our GA releases: Our approach to the site has changed a lot in the past several months, to be strictly marketing focused and not something that needs to be a direct parity of the internal catalog, thus reducing the complexity. 
- This site is transitioning to a team focused on marketing website development, and SSR and an integration with the catalog service is extra complexity that offers little end user value, for just a marketing site
